name: todos
description: Simple todo app with an offline-first approach

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: 0.10.1
  injectable: 2.0.1
  drift: 2.2.0
  retrofit: '>=3.0.0 <4.0.0'
  logger: any
  dio: ^4.0.6
  json_annotation: ^4.0.0
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  flutter_spinkit: 5.1.0

dev_dependencies:
  build_runner: any
  injectable_generator: 2.0.1
  retrofit_generator: '>=4.0.0 <5.0.0'
  json_serializable: '>4.4.0'
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true